# ============================================================================
# LOCATION REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-10-21 09:20:55 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.location import LocationUpdate, LocationCreate, LocationOut

async def create_location(location_data: LocationCreate) -> LocationOut:
    location_dict = location_data.model_dump()
    result =await db.locations.insert_one(location_dict)
    result = await db.locations.find_one(filter={"_id":result.inserted_id})
    returnable_result = LocationOut(**result)
    return returnable_result

async def get_location(filter_dict: dict) -> Optional[LocationOut]:
    try:
        result = await db.locations.find_one(filter_dict)

        if result is None:
            return None

        return LocationOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching location: {str(e)}"
        )
    
async def get_locations(filter_dict: dict = {},start=0,stop=100) -> List[LocationOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.locations.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        location_list = []

        async for doc in cursor:
            location_list.append(LocationOut(**doc))

        return location_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching locations: {str(e)}"
        )
async def update_location(filter_dict: dict, location_data: LocationUpdate) -> LocationOut:
    result = await db.locations.find_one_and_update(
        filter_dict,
        {"$set": location_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = LocationOut(**result)
    return returnable_result

async def delete_location(filter_dict: dict):
    return await db.locations.delete_one(filter_dict)